dist: trusty
language: python
python:
  - "3.5.3"
  - "3.6.1"
install:
  - echo "pytest>3" >> requirements.txt
  - echo "pyyaml" >> requirements.txt
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python -m pytest
cache: pip
notifications:
  email: false